name: $(Build.DefinitionName)_$(Date:yyyyMMdd)$(Rev:.r)

resources:
  repositories:
    - repository: release-engine-core # REPOSITORY ALIAS ###  MUST NOT  ### BE CHANGED
      type: github
      name: thecloudexplorers/release-engine-core # RELEASE ENGINE REPOSITORY ###  MUST NOT  ### BE CHANGED
      endpoint: thecloudexplorers
      ref: refs/tags/v1.5.0

    - repository: workload # REPOSITORY ALIAS ###  MUST NOT  ### BE CHANGED
      type: github
      name: thecloudexplorers/release-engine-pattern-template
      endpoint: thecloudexplorers
      ref: refs/heads/users/wcamargo/update-patterns-examples

trigger:
  - main
  - users/*

pool: MSHosted-WorkloadsPool

extends:
  template: /patterns/resource_group_scope_pattern/workload.yml@workload
  parameters:
    platformWorkloadSettings:
      configurationFilePath: /_config

      environments:
        - name: development
          dependsOn: build
          displayName: Dev
          primaryEnvironment: true
        # - name: test
        #   dependsOn: development
        #   displayName: Test
        # - name: production
        #   dependsOn: test
        #   displayName: Prod
